-- AlterTable
ALTER TABLE "IRRIGATION_PROFILE" ADD COLUMN     "user_id" TEXT;

-- AlterTable
ALTER TABLE "SCHEDULE" ADD COLUMN     "user_id" TEXT;

-- AddForeignKey
ALTER TABLE "IRRIGATION_PROFILE" ADD CONSTRAINT "IRRIGATION_PROFILE_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USER"("user_id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCHEDULE" ADD CONSTRAINT "SCHEDULE_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USER"("user_id") ON DELETE SET NULL ON UPDATE CASCADE;
