-- CreateEnum
CREATE TYPE "DeviceType" AS ENUM ('SOIL_MOISTURE_SENSOR', 'DHT20_TEMPERATURE_SENSOR', 'DHT20_HUMIDITY_SENSOR', 'RELAY_MODULE', 'LCD_16X2_DISPLAY', 'ESP32');

-- AlterTable
ALTER TABLE "DEVICE" DROP COLUMN "device_type";
ALTER TABLE "DEVICE" ADD COLUMN "device_type" "DeviceType";
ALTER TABLE "DEVICE" ADD COLUMN "feed_key" TEXT;
